---
title: "Glossary of Terms"
linkTitle: "Glossary"
weight: 99
---

:toc:
:toclevels:     3

== Primary:
=== *Attribute* +
See 'UOR Attribute'. +

=== *OCI-shim* +
OCI Distribution implementation of UOR Provider Integration +

=== *UOR* +
See 'Universal Object Reference'. +

=== *Universal Object Reference*. +
A standardized approach to writing object descriptions. +

=== *UOR Attribute* +
The nature of an object possessing an quality expressed as a key/value pair. Attributes may be either positive, as in "color=blue is true" or negative, as in "color=blue is false" to expressly describe the attribute as being the opposite of the descriptive key/value pair. Attributes can be any typed annotation (int, string, bool, ...) +

=== *UOR Artifact* +
A UOR Object & UOR Attribute Manifest Dataset. +

=== *UOR Artifact Manifest* +
A UOR Artifact Manifest is a UOR Artifact that contains an index of UOR Objects. +

=== *UOR Artifact Dependency* +
A UOR Artifact that is referenced by another UOR Artifact. +

=== *UOR Object* +
An UOR Artifact as described by it's associated UOR Artifact manifest. The object may be of any type and may itself be a UOR Artifact. +

=== *SECONDARY OBJECT SETS* +
Large Object Sets which could theoretically be indicated by Secondary Satellite Sets. If observed, it is highly recommended to carefully study for Digital Intuition research possibilities. +

=== *PRIMARY ATTRIBUTE* +
An attribute shared by objects with a shared schema. +

=== *CORRELATED ATTRIBUTES* +
Two or more Attribute sets which share common Object(s) and are separated by 3 degrees or less of non-explicit corelation. +

=== *SECONDARY ATTRIBUTE SETS* +
Correlated Attributes that are separated by more than 3 degrees of non-explicit corelation. +

=== *THREAD* +
The shortest path between client and object. +

=== *ROUTE* +
A path of UOR relations that following an attribute thread. +

=== *GRAPH* +
A graph is a fully assembled UOR Artifact Route manifest honoring all attributable child manifests. +

=== *VERTEX* +
The intersect of two route paths. +

=== *ORBIT* +
The path of a UOR route which references back upon itself via one or more hops. This is one collision vector risk type which must be accounted for by safety mechanisms such as spanning tree type protections. +

=== *SATELLITE* +
An Attribute observed to form any Orbit by first, second, or subsequent degrees of non-explicit corelation to other objects by first, second, or third degree secondary attributes. Attribute correlation separated by more than 3 degrees of non-explicit corelation are considered loosely coupled Secondary Attribute Sets and currently considered non-candidates for significant study. +

=== *UR* +
See "Universal Runtime". +

=== *Universal Runtime* +
Universal Runtime (UR) is the runtime framework built into UOR. The dynamic nature of UR is a result of being able to consume and act on the contents of an Artifact. UR can assemble one or many Artifact's Manifests, Specs, and Objects into a fully operational instruction.

=== *URO* +
Universal Runtime Object. +

A Universal Runtime Object is an executable UOR Object that may be a binary, script, or other computer operable instruction. +

=== *URC* +
Universal Reference Client. +

Universal Reference Client is a standard for creating UOR compatible clients. A UOR compatible client should be able to ... & intelligently inform a URi to act on runtime Artifacts. +

=== *Universal Runtime Interface* +
Universal Runtime Interface (URi) is a standard for implementing Universal Runtime. A URi is the host process responsible for the execution of a Universal Runtime Object. +

=== *URS* +
See Universal Runtime Scheduler. +

=== *Universal Runtime Scheduler* +
Universal Runtime Scheduler is a standard for scheduling UROs to be executed by a URi. +

=== *UrOS* +
See Universal Runtime Operating System. +

=== *Universal Runtime Operating System* +
Universal Runtime Operating System (UrOS) is a reference Operating system for Universal Runtime. +

=== *Sliding Attribute Scale* +
An imperfect attribute boolean that is represented by a sliding confidence scale of 0-1000 representing the degree of confidence in boolean state. +

In the confidence scale, absolute confidence is expressed as 1000 and the least confident is 0. The negative range of confidence is used to represent the degree of certainty based on contextual information. +

=== *Attribute Inheritance*
A UOR Attribute that is inherited by contextual awareness in UOR query criteria. +

== Tertiary: +
=== *Neutrino* +
A minimal operating system that is capable of running a UOR Client & URO(s). +

=== *Qubit* +
The non-hardware scoped subset of the Neutrino operating system that is capable of running a UOR Client & URO(s). It's smallest unit of implementation is the Qubit Linux Container. +

=== *ORBITS* +
The collection of all possible ORBITs of an Object. +

=== *SUSPECT*
A UOR Object which is identified by it's corelation to orbiting Satellite attributes. Suspect objects are uniquely valid for corelation model study and predictive test rigor testing. +

=== *SATELLITES* +
A collection of all possible Satellite Attributes of an Object. +

=== *SECONDARY SATELLITE SETS* +
Large Satellite Sets which could theoretically Orbit in a swarm formation around clearly defined Secondary Attribute Sets or Secondary Object Sets. If observed, it is highly recommended to carefully study for Digital Implication research possibilities. +

=== *ORDINAL PRIMARY ATTRIBUTE*
A UOR Attribute that denotes a hierarchical superposition spiral over itself or other Objects caused by a runaway Orbit. This is a theoretical scenario which if encountered should be handled with extreme care. +

=== *Self Organizing Digital Cognition*
Self-organizing digital cognition is a new approach to digital cognition that uses a self-organizing map to learn and recognize patterns in digital data, and then use the learned patterns to make predictions. +

=== *DAG*
Directed Acyclic Graph. A graph that is acyclic and has no cycles. +

=== *ORAS*
Object Registry As Storage. +

=== *OCI Artifact*
An OCI Artifact is a single data object that is stored in an OCI Registry. This may be a container, blob, ASCII object, video, image, or other media. +