---
title: "Example Use-Cases"
linkTitle: "Use-Cases"
weight: 3
categories: ["quickstart", "uor"]
tags: ["edu","docs"]
description: >
  A short list of some example use-cases for UOR.
---

== UOR Example Use-Cases
:toc:
:toclevels: 3
:sectnumlevels: 3

### File Management:

UOR can be used to store and retrieve any arbitrary files. The files can be retrieved by name (since name is just an attribute) or the files can be retrieved by referencing their other attributes. 

#### For example: 
A user stores files within a UOR collection and queries the UOR collection for a file called “fish.jpeg”. The user then wants to discover all configuration files held within the UOR collection, so they query the UOR collection for all configuration files. The user can further specify the configuration file(s) for a specific application within their query. 

### Labeling and Dataset Management:

Similar to the example above, UOR can be used to label, store, and retrieve datasets used in MLOps.

#### For example: 
A dataset containing images with COCO (https://cocodataset.org/#format-data) annotations applied can be stored as a UOR collection and subsets of the dataset can be retrieved by referencing any individual or collection of COCO annotation(s). 

### Websites/web apps:

Universal Runtime Objects (UROs) make UOR an inherently serverless framework. In the case of websites/web apps, a lightweight web/app server is embedded with UOR formatted web content. 

#### For example: 
A user browses to a UOR formatted website, the web browser executes the lightweight web or application server which contains the logic to serve the corresponding content. Is then served to the browser engine where it is rendered. 

The web/app server can be reused/shared between UOR collections containing websites. 

### Infrastructure Provisioning

A cloud infrastructure configuration can be stored within a UOR collection along with a utility used to process that configuration. When the utility makes actions based upon the associated config, it can write its state information back to the original collection.

#### For example: 
A user retrieves a UOR collection containing a Terraform configuration. The Terraform binary is embedded in that collection. The terraform binary is executed against the referenced configuration and after processing, the tfstate is written back to the collection. 




